---
title: "Basic Calculus Review"
linktitle: "Math prerequisites"
output:
  blogdown::html_page:
    toc: false
menu:
  resource:
    parent: Math Review
    weight: 1
type: docs
---

Throughout the course, we'll use a handful of elementary concepts from calculus. These basic tools are straightforward and easily mastered. In fact, you have already used calculus when you considered marginal revenue and marginal cost in your other economics classes. Here, I provide some review material to help you get back up-to-speed with the necessary mathematical concepts for this class.

## Functions
A function is just a formal way in which inputs (a functions arguments) are converted into an output. For example, a firm's total revenue (TR) is a function of the amount they produce (Q), such that: $$TR = TR(Q).$$ This means that total revenue depends on $Q$, the quantity of product produced and sold. Total cost is also a function of $Q$: $$TC = TC(Q).$$

As a more explicit example, suppose that the inverse demand for a firm is $$P = 100 - 0.10Q,$$ where $P$ denotes price and $Q$ denotes quantity. Since total revenue is the product of price and quantity, we have $$TR = P \times Q = (100 - 0.10Q) \times Q = 100Q - 0.10Q^2.$$ Thus, total revenue is a function of quantity produced and sold.

Some functions are more complicated. Producing health care, for example, requires a hospital or some facility ($x_{1}$); lots of equipment and medical supplies ($x_{2}$); and physicians, nurses, and staff ($x_{3}$). We can write the production function of hospitals as $$Q = f(x_{1}, x_{2}, x_{3}),$$ where $Q$ denotes the "amount" of health care provided and $f()$ represents the production technology that converts inputs into outputs. 

