---
title: General information
date: "2020-12-03"
menu:
  assignment:
    parent: Assignments
    weight: 1
type: docs
weight: -1
output:
  blogdown::html_page:
    toc: true
---

Below are basic descriptions of each category of assignments for this semester. More details are available on the individual pages for each assignment.

## Homework
Please submit all of your homework answers as a PDF through **Canvas**. You can use Word and "print" to PDF, but I also encourage you to use [Overleaf](https://www.overleaf.com/), which will help you to easily create PDFs and is much better for writing math-oriented documents. Overleaf is also fully cloud-based, and as an Emory student, you have full access to Overleaf Professional. 

Each homework assignment is worth 60 points toward your final grade. Each homework assignment will have 20 individual parts (think 4 or 5 questions each with 4 or 5 individual components), so you should expect each part of each question to be worth 3 points. Each part will be graded as follows:

- **3 points:** Correct answer
- **2 points:** Good try and close, but with minor mistakes
- **1 point:** Incomplete work but an attempt nonetheless
- **0 points:** No work toward the answer (e.g., completely blank or some initial equation written without any attempt to solve)


## Exam
We only have one exam this semester, and it will cover content from Modules 1 and 2. The exam is worth 60 points toward your final grade. Please see the [Mid-term Exam](/assignment/exam1/) page for more details. 

## Project
We do not have a final exam in this class. Instead, we have a final project that asks you to use real data and interpret some summary statistics in the context of the material we've covered in class. The final project is due on the date of our final exam, which is May 12th this year. The project is worth 140 points toward your final grade.

Please see the [Final Project](/assignment/project/) for more details.

## Participation
"Participation" in each week will be graded based on how many of the weekly participation elements are submitted, specifically: 

- **2 points:** Submission of a weekly check-in and completion of in-class "quiz"
- **1 point:** Submission of the check-in or completion of the quiz, but not both
- **0 points:** No submission of a check-in and no completion of the quiz

Your final participation grade in the class is worth 20 points toward your final grade. We have 14 weeks of class this semester, which means you'll have well over 20 total "participation" points available. So you have some margin for error here.